name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Use latest version

      - name: Setup Node
        uses: actions/setup-node@v4 # Use latest version
        with:
          node-version: "20" # Use Node.js 20

      - name: Install dependencies
        run: |
          cd app       # Navigate to the app directory
          npm install  # Install dependencies

      - name: Build project
        run: |
          cd app       # Navigate to the app directory
          npm run build  # Build the project

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # Update to v4
        with:
          name: production-files
          path: app/dist # Correct path to the build folder

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # Update to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Update to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Ensure the correct path is referenced
